// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAkY4J_FUfWnKkHde5arMnTPy0sFvnaTU',
    appId: '1:496002664205:web:94cfee48b91e358a999244',
    messagingSenderId: '496002664205',
    projectId: 'car-rental-app-263b6',
    authDomain: 'car-rental-app-263b6.firebaseapp.com',
    storageBucket: 'car-rental-app-263b6.appspot.com',
    measurementId: 'G-6EMV33C1CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWnHrArdDrOo0xiJlMxFR7mrKeQ8l8j2w',
    appId: '1:496002664205:android:bc90139c2e4af035999244',
    messagingSenderId: '496002664205',
    projectId: 'car-rental-app-263b6',
    storageBucket: 'car-rental-app-263b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEyntCaFhF5NyIuLDmeA_zE7VWkm2jfjs',
    appId: '1:496002664205:ios:0b3033b154b36643999244',
    messagingSenderId: '496002664205',
    projectId: 'car-rental-app-263b6',
    storageBucket: 'car-rental-app-263b6.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );
}
